import { jsPDF } from 'jspdf';
import { AuditReport, AuditIssue, CrawledPageResult } from '../../server/crawler';

export interface AuditPdfOptions {
  companyName?: string;
  generatedBy?: string;
}

export function generateSeoAuditPdf(report: AuditReport, options: AuditPdfOptions = {}): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  let cursorY = margin;

  const generatedDate = report.crawledAt
    ? new Date(report.crawledAt).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      })
    : new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });

  const auditor = options.generatedBy || 'Indexer Engine Technical SEO System';

  // Helper to ensure vertical space and handle multi-page splitting
  const ensureSpace = (neededHeight: number) => {
    if (cursorY + neededHeight > pageHeight - margin - 12) {
      doc.addPage();
      cursorY = margin + 10;
      drawRunningHeaderFooter();
    }
  };

  const drawRunningHeaderFooter = () => {
    const pageNum = doc.getNumberOfPages();
    if (pageNum > 1) {
      // Running Top Header
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(130, 140, 160);
      doc.text(`Technical SEO & Crawl Audit Report — ${report.targetDomain}`, margin, 11);
      doc.text(`Health Score: ${report.healthScore}/100`, pageWidth - margin - 32, 11);
      doc.setDrawColor(220, 225, 235);
      doc.setLineWidth(0.3);
      doc.line(margin, 13, pageWidth - margin, 13);

      // Running Bottom Footer
      doc.setDrawColor(220, 225, 235);
      doc.setLineWidth(0.3);
      doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
      doc.setFontSize(8);
      doc.setTextColor(140, 145, 160);
      doc.text(`Confidential • Generated by ${auditor}`, margin, pageHeight - 8);
      doc.text(`Page ${pageNum}`, pageWidth - margin - 14, pageHeight - 8);
    }
  };

  // ==========================================
  // 1. TOP COVER / BANNER
  // ==========================================
  doc.setFillColor(17, 17, 19); // #111113 dark ink
  doc.roundedRect(margin, cursorY, contentWidth, 42, 3, 3, 'F');

  // Accent badge
  doc.setFillColor(255, 77, 0); // #ff4d00 accent
  doc.roundedRect(margin + 6, cursorY + 6, 26, 6, 1.5, 1.5, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.text('SEO AUDIT', margin + 8, cursorY + 10.3);

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text(`Technical Website Crawl Audit`, margin + 36, cursorY + 11);

  // Subtitle / Target Domain
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(200, 210, 225);
  doc.text(`Target Domain: ${report.targetDomain} (${report.baseURL})`, margin + 6, cursorY + 22);

  // Timestamp and Crawl scope
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Crawled Pages: ${report.totalPagesCrawled}  •  Date: ${generatedDate}  •  Engine: AutoSubmit Pro Crawler v2.4`,
    margin + 6,
    cursorY + 32
  );

  // Health Score Box (Right Side)
  const scoreX = pageWidth - margin - 42;
  const isGood = report.healthScore >= 80;
  const isMed = report.healthScore >= 50 && report.healthScore < 80;
  doc.setFillColor(isGood ? 16 : isMed ? 217 : 225, isGood ? 185 : isMed ? 119 : 29, isGood ? 129 : isMed ? 6 : 72);
  doc.roundedRect(scoreX, cursorY + 6, 36, 30, 2.5, 2.5, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.text('HEALTH SCORE', scoreX + 4.5, cursorY + 12);

  doc.setFontSize(16);
  doc.text(`${report.healthScore}`, scoreX + 7, cursorY + 23);
  doc.setFontSize(9);
  doc.text('/100', scoreX + 22, cursorY + 23);

  doc.setFontSize(6.5);
  doc.text(isGood ? 'OPTIMAL' : isMed ? 'NEEDS ATTENTION' : 'CRITICAL', scoreX + 4.5, cursorY + 31);

  cursorY += 48;

  // ==========================================
  // 2. EXECUTIVE METRICS KPI GRID
  // ==========================================
  ensureSpace(24);
  const colWidth = (contentWidth - 12) / 4;

  const metrics = [
    { label: 'TOTAL ISSUES', val: `${report.summary.totalIssues}`, color: [17, 24, 39], bg: [243, 244, 246] },
    { label: 'HIGH IMPACT', val: `${report.summary.highImpactCount}`, color: [225, 29, 72], bg: [255, 241, 242] },
    { label: 'MEDIUM IMPACT', val: `${report.summary.mediumImpactCount}`, color: [217, 119, 6], bg: [254, 243, 199] },
    { label: 'AVG SPEED', val: `${Math.round(report.summary.avgResponseTimeMs || 0)}ms`, color: [16, 185, 129], bg: [236, 253, 245] },
  ];

  metrics.forEach((m, idx) => {
    const x = margin + idx * (colWidth + 4);
    doc.setFillColor(m.bg[0], m.bg[1], m.bg[2]);
    doc.setDrawColor(229, 231, 235);
    doc.setLineWidth(0.3);
    doc.roundedRect(x, cursorY, colWidth, 18, 2, 2, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(6.5);
    doc.setTextColor(100, 116, 139);
    doc.text(m.label, x + 3.5, cursorY + 5.5);

    doc.setFontSize(11);
    doc.setTextColor(m.color[0], m.color[1], m.color[2]);
    doc.text(m.val, x + 3.5, cursorY + 13.5);
  });

  cursorY += 24;

  // ==========================================
  // 3. EXECUTIVE SUMMARY CALLOUT
  // ==========================================
  ensureSpace(26);
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.4);
  doc.roundedRect(margin, cursorY, contentWidth, 24, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text('EXECUTIVE AUDIT SUMMARY', margin + 5, cursorY + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(51, 65, 85);

  let summaryDesc = `The technical crawler analyzed ${report.totalPagesCrawled} pages on ${report.targetDomain}. Overall site health is rated at ${report.healthScore}/100 with ${report.summary.highImpactCount} high-priority issues and ${report.summary.brokenLinksCount || 0} broken links detected.`;
  if (report.summary.missingAltCount > 0) {
    summaryDesc += ` ${report.summary.missingAltCount} images lack accessible alt attributes.`;
  }
  if (report.summary.noIndexCount > 0) {
    summaryDesc += ` ${report.summary.noIndexCount} pages have active noindex directives.`;
  }

  const splitSummary = doc.splitTextToSize(summaryDesc, contentWidth - 10);
  doc.text(splitSummary, margin + 5, cursorY + 12);

  cursorY += 30;

  // ==========================================
  // 4. CRITICAL & HIGH-IMPACT ISSUES
  // ==========================================
  const highIssues = report.issuesByImpact?.high || [];
  if (highIssues.length > 0) {
    ensureSpace(20);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(225, 29, 72); // Rose
    doc.text(`Critical & High-Impact Issues (${highIssues.length})`, margin, cursorY);
    cursorY += 5;

    highIssues.forEach((issue: AuditIssue, idx: number) => {
      ensureSpace(18);

      doc.setFillColor(255, 245, 245);
      doc.setDrawColor(254, 205, 211);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin, cursorY, contentWidth, 15, 1.5, 1.5, 'FD');

      // Left red accent bar
      doc.setFillColor(225, 29, 72);
      doc.rect(margin, cursorY, 2.5, 15, 'F');

      // Issue Title & Type
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(159, 18, 57);
      doc.text(`${idx + 1}. ${issue.title || issue.type}`, margin + 5, cursorY + 5);

      // URL
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(100, 116, 139);
      const urlText = issue.url ? `URL: ${issue.url}` : '';
      const splitUrl = doc.splitTextToSize(urlText, contentWidth - 10);
      doc.text(splitUrl[0] || '', margin + 5, cursorY + 9);

      // Description / Details
      doc.setTextColor(71, 85, 105);
      const descText = issue.description || issue.details || '';
      const splitDesc = doc.splitTextToSize(descText, contentWidth - 10);
      doc.text(splitDesc[0] || '', margin + 5, cursorY + 13);

      cursorY += 18;
    });
    cursorY += 4;
  }

  // ==========================================
  // 5. MEDIUM & LOW IMPACT ISSUES (SUMMARY TABLE)
  // ==========================================
  const mediumIssues = report.issuesByImpact?.medium || [];
  const lowIssues = report.issuesByImpact?.low || [];
  const otherIssues = [...mediumIssues, ...lowIssues];

  if (otherIssues.length > 0) {
    ensureSpace(20);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.text(`Medium & Minor SEO Findings (${otherIssues.length})`, margin, cursorY);
    cursorY += 6;

    // Table Header
    doc.setFillColor(241, 245, 249);
    doc.rect(margin, cursorY, contentWidth, 6, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(71, 85, 105);
    doc.text('SEVERITY', margin + 3, cursorY + 4.2);
    doc.text('ISSUE TITLE / CATEGORY', margin + 25, cursorY + 4.2);
    doc.text('AFFECTED URL / DESCRIPTION', margin + 85, cursorY + 4.2);
    cursorY += 7;

    otherIssues.slice(0, 15).forEach((issue: AuditIssue) => {
      ensureSpace(10);

      const isMedium = issue.impact === 'MEDIUM';
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(6.5);
      doc.setTextColor(isMedium ? 217 : 56, isMedium ? 119 : 189, isMedium ? 6 : 248);
      doc.text(issue.impact, margin + 3, cursorY + 4);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.setTextColor(30, 41, 59);
      const titleShort = issue.title.length > 32 ? issue.title.slice(0, 32) + '...' : issue.title;
      doc.text(titleShort, margin + 25, cursorY + 4);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.5);
      doc.setTextColor(100, 116, 139);
      const urlShort = issue.url.replace(/^https?:\/\/[^/]+/, '') || issue.url;
      const descLine = `${urlShort ? urlShort + ' — ' : ''}${issue.description || ''}`;
      const splitDesc = doc.splitTextToSize(descLine, contentWidth - 88);
      doc.text(splitDesc[0] || '', margin + 85, cursorY + 4);

      // Divider line
      doc.setDrawColor(241, 245, 249);
      doc.setLineWidth(0.2);
      doc.line(margin, cursorY + 6.5, pageWidth - margin, cursorY + 6.5);

      cursorY += 7.5;
    });

    if (otherIssues.length > 15) {
      ensureSpace(8);
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(7);
      doc.setTextColor(148, 163, 184);
      doc.text(`+ ${otherIssues.length - 15} additional minor findings listed in complete JSON export.`, margin + 3, cursorY + 4);
      cursorY += 8;
    }
    cursorY += 4;
  }

  // ==========================================
  // 6. CRAWLED PAGES SAMPLE TABLE
  // ==========================================
  if (report.pages && report.pages.length > 0) {
    ensureSpace(24);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 41, 59);
    doc.text(`Crawled Pages Sample (${Math.min(report.pages.length, 10)} of ${report.pages.length})`, margin, cursorY);
    cursorY += 6;

    // Header
    doc.setFillColor(241, 245, 249);
    doc.rect(margin, cursorY, contentWidth, 6, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(7);
    doc.setTextColor(71, 85, 105);
    doc.text('STATUS', margin + 3, cursorY + 4.2);
    doc.text('RESPONSE', margin + 20, cursorY + 4.2);
    doc.text('PAGE TITLE / URL PATH', margin + 42, cursorY + 4.2);
    doc.text('ISSUES', pageWidth - margin - 18, cursorY + 4.2);
    cursorY += 7;

    report.pages.slice(0, 10).forEach((page: CrawledPageResult) => {
      ensureSpace(11);

      // Status badge
      const is200 = page.statusCode >= 200 && page.statusCode < 300;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(is200 ? 16 : 225, is200 ? 185 : 29, is200 ? 129 : 72);
      doc.text(`HTTP ${page.statusCode}`, margin + 3, cursorY + 4);

      // Response Time
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.5);
      doc.setTextColor(100, 116, 139);
      doc.text(`${page.responseTimeMs}ms`, margin + 20, cursorY + 4);

      // Title & Path
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.setTextColor(30, 41, 59);
      const title = page.title || '(No Title Tag)';
      const shortTitle = title.length > 40 ? title.slice(0, 40) + '...' : title;
      doc.text(shortTitle, margin + 42, cursorY + 3.5);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6);
      doc.setTextColor(148, 163, 184);
      const shortUrl = page.url.length > 55 ? page.url.slice(0, 55) + '...' : page.url;
      doc.text(shortUrl, margin + 42, cursorY + 7.5);

      // Issues count
      const issueCount = page.issues?.length || 0;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.setTextColor(issueCount > 0 ? 225 : 16, issueCount > 0 ? 29 : 185, issueCount > 0 ? 72 : 129);
      doc.text(`${issueCount} flag${issueCount === 1 ? '' : 's'}`, pageWidth - margin - 18, cursorY + 4);

      // Row divider
      doc.setDrawColor(241, 245, 249);
      doc.setLineWidth(0.2);
      doc.line(margin, cursorY + 9.5, pageWidth - margin, cursorY + 9.5);

      cursorY += 10.5;
    });
    cursorY += 4;
  }

  // ==========================================
  // 7. ACTIONABLE REMEDIATION ROADMAP
  // ==========================================
  ensureSpace(34);

  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.roundedRect(margin, cursorY, contentWidth, 32, 2, 2, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text('ACTIONABLE SEO & GEO REMEDIATION CHECKLIST', margin + 5, cursorY + 6);

  const checklistItems = [
    '1. Correct High-Impact Technical Errors: Fix 404 pages, resolve duplicate H1s, and populate missing <title> and meta tags.',
    '2. Image Accessibility & SEO: Add descriptive alt attributes to all uncaptioned media assets to maximize Google Image Indexing.',
    '3. AI Search Readiness (GEO): Ensure structured Schema.org JSON-LD data exists for articles, FAQs, and organization profiles.',
    '4. Automated Indexing Push: Queue modified URLs through the Indexer Engine 5-Step Wizard for immediate Google & IndexNow pinging.',
  ];

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(51, 65, 85);
  checklistItems.forEach((item, i) => {
    doc.text(item, margin + 5, cursorY + 12 + i * 4.5);
  });

  cursorY += 36;

  // Final Header/Footer pass across all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    // Running Bottom Footer
    doc.setDrawColor(220, 225, 235);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(140, 145, 160);
    doc.text(`Confidential Technical SEO Audit • ${report.targetDomain} • ${generatedDate}`, margin, pageHeight - 8);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 18, pageHeight - 8);
  }

  return doc;
}
